openapi: 3.1.0
info:
  title: Unidades
  version: 0.2.0
paths:
  /root:
    get:
      summary: GET /root
      operationId: get_root
      responses:
        '200':
          description: Success
        '500':
          description: Internal Server Error
    post:
      summary: POST /root
      operationId: post_root
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
  /root/units:
    get:
      summary: GET /root/units
      operationId: get_res_1775114007819
      responses:
        '200':
          description: Success
        '500':
          description: Internal Server Error
    post:
      summary: POST /root/units
      operationId: post_res_1775114007819
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
  /root/units/{id}/details:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
        description: Identificador global de la unidad
    get:
      summary: GET /root/units/{id}/details
      operationId: get_res_1775114050747
      responses:
        '200':
          description: Success
        '500':
          description: Internal Server Error
    post:
      summary: POST /root/units/{id}/details
      operationId: post_res_1775114050747
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
    put:
      summary: PUT /root/units/{id}/details
      operationId: put_res_1775114050747
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
    delete:
      summary: DELETE /root/units/{id}/details
      operationId: delete_res_1775114050747
      responses:
        '200':
          description: Success
        '500':
          description: Internal Server Error
  /root/types:
    get:
      summary: GET /root/types
      operationId: get_res_1775114335119
      responses:
        '200':
          description: Success
        '500':
          description: Internal Server Error
    post:
      summary: POST /root/types
      operationId: post_res_1775114335119
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
  /root/types/{id}/details:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
        description: Identificador unico del tipo de unidad
    get:
      summary: GET /root/types/{id}/details
      operationId: get_res_1775114379492
      responses:
        '200':
          description: Success
        '500':
          description: Internal Server Error
    put:
      summary: PUT /root/types/{id}/details
      operationId: put_res_1775114379492
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
    delete:
      summary: DELETE /root/types/{id}/details
      operationId: delete_res_1775114379492
      responses:
        '200':
          description: Success
        '500':
          description: Internal Server Error
